### PR TITLE
Added exclude path option

### PR DESCRIPTION
**Pull request by citius**
This option allows set exclude paths from JWT check

### CODE REVIEW

**Comment by stiang** [comment]
Thanks, looks good! Mind updating the docs as well? Very busy, would appreciate the help :)

**Comment by Foxandxss** [comment]
I was thinking about creating a `koa-unless` (based on https://github.com/jfromaniello/express-unless) and then add the support for that in here. So we can achieve the same API (in KOA ways) than https://github.com/auth0/express-jwt

This way also works, and please if you plan on merging it, at least add tests @citius .

**Comment by citius** [comment]
@Foxandxss koa-unless It would be great! And I think same API for both express-jwt and koa-jwt is main priority, but this useful as option parameter too. I can add tests if this is necessary.

**Comment by Foxandxss** [comment]
Hey @citius and @stiang.

I created [koa-unless](https://github.com/Foxandxss/koa-unless) and I think that for the sake of having a good Koa version of express-jwt, we could swap this functionality to use `koa-unless`. It should be just two lines of code.

What do you think?

After that we could start porting over the other features.

**Comment by stiang** [comment]
Hi @Foxandxss and @citius,

I don’t use this functionality myself and I don’t really have a strong opinion, but I think a modular approach (using koa-unless) makes the most sense. @citius, is there any downside to this from your point of view?

**Comment by Foxandxss** [comment]
@stiang So, there are a couple of ways to do this.

In my humble opinion, one of the downsides of KOA is not having the same number of libraries as express, and well, we have this library for JWT, but the functionality is pretty limited compared to `express-jwt`.

I wanted to create my own `koa-jwt`, but I discovered this one already and it is not a good idea to duplicate work.

So one of the features of `express-jwt` is the ability to apply the middleware conditionally. It uses `express-unless` so I replicated it to koa.

So there are two options:

If we want to provide a fully featured `koa-jwt` as `express-jwt`, we just need to save our `jwt` middleware in a variable, assign the `unless` functionality to it and return it. 2 extra lines, and one modification.

The other option is having end users pull `koa-unless` and `koa-jwt` and mix them there.

To be honest, both ways works, but I still think that we could improve this library to provide all the features that `express-jwt` has on it. And this is one of them.

**Comment by citius** [comment]
@stiang 
> ...is there any downside to this from your point of view? 

nope, but the feature to ignore paths via option parameter would be useful too, as for me. But you decide, of course.

**Comment by Foxandxss** [comment]
@citius what would give you the option parameter that `unless` does not? It is the same idea but with more options.

**Comment by citius** [comment]
@Foxandxss okay, okay :) but what is wrong in it?

**Comment by Foxandxss** [comment]
Your implementation is correct. Works as intended, but with `koa-unless` it does the same but more.

What I ask you is.. isn't koa-unless enough for your use case?

**Comment by citius** [comment]
@Foxandxss The `koa-unless` is total fit for my use case. But I think option is easy to use in general config for `koa-jwt`

```js
var cfg = {};
app.use(jwt(cfg));
```

**Comment by Foxandxss** [comment]
I can agree that that is easier than:

```javascript
var cfg = {};
var unlessCfg = {};
app.use(jwt(cfg).unless(unlessCfg));
```

I just want to have the same implementation that `express-jwt` has, so when a user migrates from `express`, they can use the same kind of interface.

**Comment by stiang** [comment]
I think it makes the most sense to mimic express-jwt here, so I went with the koa-unless solution. Thanks for your efforts nonetheless!

**Pull request closed without merging**
