### PR TITLE
add dynamic aud and iss and change status to 500 for error secret

### PR DESCRIPTION
**Pull request by Jackong**

### CODE REVIEW

**Comment by DiknT** [comment]
401 Unauthorized is the correct response for missing or bad authentication, while 500 is for internal server error only. From the RFC: If the request already included Authorization credentials, then the 401 response indicates that authorization has been refused for those credentials.

**Comment by Jackong** [comment]
You may be right. but, it is internal server error, if the secret is missing.
right?

**Comment by DiknT** [comment]
I don't think so. The server is working correctly and refuses authentication when the secret is missing. There is no server error at all, the error is on the user/client side for not submitting a password with his login request.

**Comment by Jackong** [comment]
You've convinced me.
And, it may not be necessary to add `dynamic aud and iss`.
I will close this pull request.
Thanks~

**Comment by DiknT** [comment]
@Jackong you were totally right on this, it is a server error and should therefore respond with error code 500 because no jwt secret for token verification is available on the server side. I mixed this up with the login credentials... sorry for the confusion ;)

**Pull request closed without merging**
